#!/bin/bash
# dmtcp_cleanup - run at job exit
#
# Copyright 2012 Orion Poplawski <orion@cora.nwra.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Get the base from the config file
eval `grep ^ckpt_dir= $SGE_JOB_SPOOL_DIR/config`
CKPTDIR=${ckpt_dir}/${JOB_ID}.${SGE_TASK_ID/undefined/1}

# Cleanup the proper *.dmtcp checkpoint files in the current directory
eval `grep ^given_ckpt_files= ${CKPTDIR}/dmtcp_restart_script.sh`
rm $given_ckpt_files

# Remove dmtcp checkpoint directory
rm -r ${CKPTDIR}

# Always exit true
exit 0
